using UnityEditor;
using System.IO;
using UnityEngine;

namespace MetaverseCloudEngine.Unity.FixingOtherPeoplesCode
{
    internal static class DisableConvaiForIOS
    {
        [InitializeOnLoadMethod]
        public static void PatchCode()
        {
            var isItOkToOverwriteFiles = false;
            if (!Directory.Exists("Assets/Convai")) return;
            var files = Directory.GetFiles("Assets/Convai", "*.cs", SearchOption.AllDirectories);
            if (files.Length != 0)
            {
                foreach (var file in files)
                {
                    var text = File.ReadAllText(file);
                    const string symbol = "#if !UNITY_IOS // Generated by Metaverse Cloud Engine SDK";
                    if (text.Contains(symbol)) continue;
                    if (CheckIsItOkToOverwrite(ref isItOkToOverwriteFiles)) return;
                    text = symbol + "\n" + text + "\n#endif // " + symbol;
                    File.WriteAllText(file, text);
                    Debug.Log($"Fixed Convai file: {file}");
                }
            }

            files = Directory.GetFiles("Assets/Convai/Plugins", "*", SearchOption.AllDirectories);
            if (files.Length > 0)
            {
                AssetDatabase.StartAssetEditing();
                try
                {
                    foreach (var file in files)
                    {
                        var assetImporter = AssetImporter.GetAtPath(file);
                        if (assetImporter == null) continue;
                        if (assetImporter is not PluginImporter pluginImporter) continue;
                        var platform = pluginImporter.GetCompatibleWithPlatform(BuildTarget.iOS);
                        if (!platform) continue;
                        if (CheckIsItOkToOverwrite(ref isItOkToOverwriteFiles)) return;
                        pluginImporter.SetCompatibleWithPlatform(BuildTarget.iOS, false);
                        pluginImporter.SaveAndReimport();
                        Debug.Log($"Disabled Convai plugin for iOS: {file}");
                    }
                }
                finally
                {
                    AssetDatabase.StopAssetEditing();
                }
            }
        }

        private static bool CheckIsItOkToOverwrite(ref bool isItOkToOverwriteFiles)
        {
            const string editorPrefsKey = "MetaverseCloudEngineSDK_DisableConvaiForIOS";
            if (EditorPrefs.GetBool(editorPrefsKey, false)) return true;
            try
            {
                if (!isItOkToOverwriteFiles && !EditorUtility.DisplayDialog(
                        "Metaverse Cloud Engine SDK - Disable Convai for iOS",
                        "Do you want to disable Convai for iOS? Convai's iOS integration and could prevent cloud builds from working.",
                        "Yes (Recommended)", "No"))
                {
                    return true;
                }
                isItOkToOverwriteFiles = true;
                return false;
            }
            finally
            {
                EditorPrefs.SetBool(editorPrefsKey, isItOkToOverwriteFiles);
            }
        }
    }
}